### ISSUE TITLE
Installing node v1.0 and greater from source is not currently supported

### ISSUE THREAD

**Issue by i5ting** [pauliusuza/node-v7-async-await-demo#3]
nvm install 7  
Downloading https://nodejs.org/download/test/v7.0.0/node-v7.0.0-darwin-x64.tar.xz...
###### ################################################################## 100.0%

WARNING: checksums are currently disabled for node.js v4.0 and later
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
Binary download failed, trying source.
Binary download failed, trying source.
###### ################################################################## 100.0%

Checksums empty
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
Binary download failed, trying source.
Installing node v1.0 and greater from source is not currently supported

**Comment by pauliusuza** [comment]
Make sure to set up mirror for NVM in order to install node, it's currently in the test branch:
`NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/test nvm install 7`

**Comment by i5ting** [comment]
thanks @pauliusuza 

another way

https://cnodejs.org/topic/580027e20bab808265185db2#58004364fdf3bd3d651185f4

```
NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly/
nvm install v7.0.0-nightly20161013e4ee09a5b3 
```
