### ISSUE TITLE
constructor?

### ISSUE THREAD

**Issue by ralyodio** [pauliusuza/node-v7-async-await-demo#5]
Is it possible to add a constructor to you ES6 class example?

I am not getting it to work:

`this` is undefined in my async method

	class DB {
	  constructor(opts){
	    this.opts = opts;
	    this.dbUrl = process.env.MONGODB_URL
	  }

	  async connect(ctx, next){
	    try {
	      ctx.db = await MongoClient.connect(this.dbUrl); // this is undefined
	    } catch(err) {
	      ctx.status = 500;
	      ctx.body = err.message || http.STATUS_CODES[ctx.status];
	    }

	    await next();
	  }

	  async close(ctx, next){
	    const result = await ctx.db.close();
	    await next();
	  }
	}

	module.exports = DB;

**Comment by pauliusuza** [comment]
Hi. Try adding this line to bind the class context to your connect function inside constructor:

```
this.connect = this.connect.bind(this);
```

**Comment by ralyodio** [comment]
hmmmm.....i solved it by doing `DB.connect.bind(DB)` on the calling side, but this seems slightly easier not to have to worry about it wherever its called.
