### ISSUE TITLE
this is weird

### ISSUE THREAD

**Issue by patrikx3** [pauliusuza/node-v7-async-await-demo#6]
why do you want arrow in class?
class a() {
  b() => {
 }
}

in fact the original is smaller:
class a() {
  b() {
 }
}

just shared why is it weird?

**Comment by pauliusuza** [comment]
Arrow functions are automatically bound to their parent class. 

So this b() =>{} 
Actually replaces this:

class a {
	constructor() {
		this.b = this.b.bind(this);
	} 
	b() {} 
}
